version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/Amsterdam"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/Amsterdam"
    groups:
      actions-dependencies:
        patterns:
          - "*"
